import { defineType, defineField } from 'sanity'

/**
 * pageContent — single document type replacing all individual page schemas.
 * pageId + language uniquely identify each document (e.g. "homepage" + "en").
 * Field visibility is controlled per-page via `hidden` callbacks.
 */

const isPage = (...pages: string[]) =>
  ({ document }: { document?: Record<string, unknown> }) =>
    !pages.includes(document?.pageId as string)

export const pageContent = defineType({
  name: 'pageContent',
  title: 'Page Content',
  type: 'document',
  groups: [
    { name: 'hero', title: 'Hero', default: true },
    { name: 'sections', title: 'Sections' },
    { name: 'seo', title: 'SEO' },
  ],
  fields: [
    // ── Identity ────────────────────────────────────────────────────────────
    defineField({ name: 'language', type: 'string', readOnly: true, hidden: true }),
    defineField({
      name: 'pageId',
      title: 'Page',
      type: 'string',
      validation: (R) => R.required(),
      options: {
        layout: 'radio',
        list: [
          { title: 'Homepage', value: 'homepage' },
          { title: 'About', value: 'aboutPage' },
          { title: 'Services', value: 'servicesPage' },
          { title: 'Work', value: 'workPage' },
          { title: 'Clients', value: 'clientsPage' },
          { title: 'Contact', value: 'contactPage' },
          { title: 'Careers', value: 'careersPage' },
          { title: 'Blog', value: 'blogPage' },
          { title: 'Privacy Policy', value: 'privacyPage' },
          { title: 'Cookie Policy', value: 'cookiePage' },
        ],
      },
    }),
    defineField({ name: 'isPublished', title: 'Published', type: 'boolean', initialValue: true }),

    // ── Hero (shared by all pages) ──────────────────────────────────────────
    defineField({ name: 'heroLabel', title: 'Hero — Eyebrow Label', type: 'string', group: 'hero' }),
    defineField({ name: 'heroHeadline', title: 'Hero — Headline', type: 'string', group: 'hero' }),
    defineField({ name: 'heroAccent', title: 'Hero — Accent Line (orange)', type: 'string', group: 'hero' }),
    defineField({ name: 'heroBody', title: 'Hero — Body Text', type: 'text', rows: 4, group: 'hero' }),
    // Homepage-specific hero fields
    defineField({ name: 'heroHeadlinePrefix', title: 'Hero — Headline Prefix (Homepage)', type: 'string', group: 'hero',
      description: 'Text before the cycling word (e.g. "We make")', hidden: isPage('homepage') }),
    defineField({ name: 'heroCyclingWords', title: 'Hero — Cycling Words (Homepage)', type: 'array', of: [{ type: 'string' }], group: 'hero',
      description: 'Rotating words (e.g. brands, events, ADS)', hidden: isPage('homepage') }),
    defineField({ name: 'heroAccentLine', title: 'Hero — Accent Line Yellow (Homepage)', type: 'string', group: 'hero',
      description: 'The yellow accent word on second line (e.g. "impossible")', hidden: isPage('homepage') }),
    defineField({ name: 'heroHeadlineSuffix', title: 'Hero — Headline Suffix (Homepage)', type: 'string', group: 'hero',
      description: 'Last line of headline (e.g. "to ignore.")', hidden: isPage('homepage') }),
    defineField({ name: 'heroSubheadline', title: 'Hero — Subheadline (Homepage)', type: 'text', rows: 3, group: 'hero',
      hidden: isPage('homepage') }),
    defineField({ name: 'heroMarqueeClients', title: 'Hero — Marquee Clients (Homepage)', type: 'array', of: [{ type: 'string' }], group: 'hero',
      description: 'Uppercase client names shown in the scrolling ticker', hidden: isPage('homepage') }),
    defineField({ name: 'heroCta1Label', title: 'Hero — CTA 1 Label', type: 'string', group: 'hero' }),
    defineField({ name: 'heroCta1Href', title: 'Hero — CTA 1 URL', type: 'string', group: 'hero' }),
    defineField({ name: 'heroCta2Label', title: 'Hero — CTA 2 Label', type: 'string', group: 'hero',
      hidden: isPage('homepage') }),
    defineField({ name: 'heroCta2Href', title: 'Hero — CTA 2 URL', type: 'string', group: 'hero',
      hidden: isPage('homepage') }),

    // ── Stats (Homepage) ────────────────────────────────────────────────────
    defineField({ name: 'stat1Value', title: 'Stat 1 — Value', type: 'string', group: 'sections', hidden: isPage('homepage'),
      description: 'Accepts any format: "+340%", "50+", "7", etc.' }),
    defineField({ name: 'stat1Label', title: 'Stat 1 — Label', type: 'string', group: 'sections', hidden: isPage('homepage') }),
    defineField({ name: 'stat2Value', title: 'Stat 2 — Value', type: 'string', group: 'sections', hidden: isPage('homepage') }),
    defineField({ name: 'stat2Label', title: 'Stat 2 — Label', type: 'string', group: 'sections', hidden: isPage('homepage') }),
    defineField({ name: 'stat3Value', title: 'Stat 3 — Value', type: 'string', group: 'sections', hidden: isPage('homepage') }),
    defineField({ name: 'stat3Label', title: 'Stat 3 — Label', type: 'string', group: 'sections', hidden: isPage('homepage') }),
    defineField({ name: 'stat4Value', title: 'Stat 4 — Value', type: 'string', group: 'sections', hidden: isPage('homepage') }),
    defineField({ name: 'stat4Label', title: 'Stat 4 — Label', type: 'string', group: 'sections', hidden: isPage('homepage') }),
    defineField({ name: 'servicesHeadline', title: 'Services Section — Headline', type: 'string', group: 'sections', hidden: isPage('homepage') }),
    defineField({ name: 'servicesBody', title: 'Services Section — Body', type: 'text', rows: 3, group: 'sections', hidden: isPage('homepage') }),
    defineField({ name: 'servicesEyebrow', title: 'Services Section — Eyebrow', type: 'string', group: 'sections', hidden: isPage('homepage') }),
    defineField({ name: 'servicesAllLabel', title: 'Services Section — "All services" label', type: 'string', group: 'sections', hidden: isPage('homepage') }),
    defineField({ name: 'servicesLearnMoreLabel', title: 'Services Section — "Learn more" label', type: 'string', group: 'sections', hidden: isPage('homepage') }),
    defineField({
      name: 'servicesList',
      title: 'Services List',
      type: 'array',
      group: 'sections',
      description: 'Editable list of services shown on Homepage preview and Services page',
      hidden: isPage('homepage', 'servicesPage'),
      of: [
        {
          type: 'object',
          name: 'serviceItem',
          fields: [
            { name: 'number', type: 'string', title: 'Number (e.g. 01)' },
            { name: 'name', type: 'string', title: 'Name' },
            { name: 'description', type: 'text', rows: 3, title: 'Description' },
            { name: 'image', type: 'image', title: 'Background Image', options: { hotspot: true } },
            { name: 'imageUrl', type: 'url', title: 'Background Image URL (external)', description: 'Use this for external image URLs' },
          ],
          preview: {
            select: { title: 'name', subtitle: 'number', media: 'image' },
          },
        },
      ],
    }),
    defineField({ name: 'clientsHeadline', title: 'Clients Section — Headline', type: 'string', group: 'sections', hidden: isPage('homepage') }),
    // Featured Work (Homepage)
    defineField({ name: 'featuredWorkLabel', title: 'Featured Work — Eyebrow Label', type: 'string', group: 'sections', hidden: isPage('homepage') }),
    defineField({ name: 'featuredWorkHeadline1', title: 'Featured Work — Headline Line 1', type: 'string', group: 'sections', hidden: isPage('homepage') }),
    defineField({ name: 'featuredWorkHeadline2', title: 'Featured Work — Headline Line 2', type: 'string', group: 'sections', hidden: isPage('homepage') }),
    defineField({ name: 'featuredWorkViewAllLabel', title: 'Featured Work — View All Link Label', type: 'string', group: 'sections', hidden: isPage('homepage') }),
    defineField({ name: 'featuredWorkViewCaseLabel', title: 'Featured Work — View Case Study Label', type: 'string', group: 'sections', hidden: isPage('homepage') }),
    defineField({ name: 'ctaSectionHeadline', title: 'CTA Section — Headline (Homepage)', type: 'string', group: 'sections', hidden: isPage('homepage') }),
    defineField({ name: 'ctaSectionBody', title: 'CTA Section — Body (Homepage)', type: 'text', rows: 3, group: 'sections', hidden: isPage('homepage') }),
    defineField({ name: 'ctaSectionButtonLabel', title: 'CTA Section — Button Label (Homepage)', type: 'string', group: 'sections', hidden: isPage('homepage') }),

    // ── Why Pota (Homepage) ─────────────────────────────────────────────────
    defineField({ name: 'whyEyebrow', title: 'Why Pota — Eyebrow', type: 'string', group: 'sections', hidden: isPage('homepage') }),
    defineField({ name: 'whyQuote', title: 'Why Pota — Quote', type: 'string', group: 'sections', hidden: isPage('homepage') }),
    defineField({ name: 'whyBody', title: 'Why Pota — Body Text', type: 'text', rows: 4, group: 'sections', hidden: isPage('homepage') }),
    defineField({ name: 'whyPoint1', title: 'Why Pota — Point 1', type: 'string', group: 'sections', hidden: isPage('homepage') }),
    defineField({ name: 'whyPoint2', title: 'Why Pota — Point 2', type: 'string', group: 'sections', hidden: isPage('homepage') }),
    defineField({ name: 'whyPoint3', title: 'Why Pota — Point 3', type: 'string', group: 'sections', hidden: isPage('homepage') }),

    // ── About — Story + Values + Team labels ────────────────────────────────
    defineField({ name: 'storyLabel', title: 'Story — Section Label', type: 'string', group: 'sections', hidden: isPage('aboutPage') }),
    defineField({ name: 'storyHeadline', title: 'Story — Headline', type: 'string', group: 'sections', hidden: isPage('aboutPage') }),
    defineField({ name: 'storyP1', title: 'Story — Paragraph 1', type: 'text', rows: 4, group: 'sections', hidden: isPage('aboutPage') }),
    defineField({ name: 'storyP2', title: 'Story — Paragraph 2', type: 'text', rows: 4, group: 'sections', hidden: isPage('aboutPage') }),
    defineField({ name: 'storyP3', title: 'Story — Paragraph 3', type: 'text', rows: 4, group: 'sections', hidden: isPage('aboutPage') }),
    defineField({ name: 'storyP4', title: 'Story — Paragraph 4', type: 'text', rows: 4, group: 'sections', hidden: isPage('aboutPage') }),
    defineField({ name: 'teamLabel', title: 'Team Section — Label', type: 'string', group: 'sections', hidden: isPage('aboutPage') }),
    defineField({ name: 'teamHeadline', title: 'Team Section — Headline', type: 'string', group: 'sections', hidden: isPage('aboutPage') }),
    defineField({ name: 'valuesLabel', title: 'Values Section — Label', type: 'string', group: 'sections', hidden: isPage('aboutPage') }),
    defineField({ name: 'valuesHeadline', title: 'Values Section — Headline', type: 'string', group: 'sections', hidden: isPage('aboutPage') }),
    defineField({ name: 'officesLabel', title: 'Offices Section — Label', type: 'string', group: 'sections',
      hidden: isPage('aboutPage', 'contactPage') }),
    defineField({ name: 'value1Title', title: 'Value 1 — Title', type: 'string', group: 'sections', hidden: isPage('aboutPage') }),
    defineField({ name: 'value1Body', title: 'Value 1 — Body', type: 'text', rows: 3, group: 'sections', hidden: isPage('aboutPage') }),
    defineField({ name: 'value2Title', title: 'Value 2 — Title', type: 'string', group: 'sections', hidden: isPage('aboutPage') }),
    defineField({ name: 'value2Body', title: 'Value 2 — Body', type: 'text', rows: 3, group: 'sections', hidden: isPage('aboutPage') }),
    defineField({ name: 'value3Title', title: 'Value 3 — Title', type: 'string', group: 'sections', hidden: isPage('aboutPage') }),
    defineField({ name: 'value3Body', title: 'Value 3 — Body', type: 'text', rows: 3, group: 'sections', hidden: isPage('aboutPage') }),
    // About offices (inline for about page — contact page uses separate fields below)
    defineField({ name: 'office1Name', title: 'Office 1 — Name', type: 'string', group: 'sections',
      hidden: isPage('aboutPage', 'contactPage') }),
    defineField({ name: 'office1Address', title: 'Office 1 — Address', type: 'string', group: 'sections',
      hidden: isPage('aboutPage', 'contactPage') }),
    defineField({ name: 'office1Country', title: 'Office 1 — Country', type: 'string', group: 'sections',
      hidden: isPage('aboutPage', 'contactPage') }),
    defineField({ name: 'office1Description', title: 'Office 1 — Description', type: 'string', group: 'sections',
      hidden: isPage('aboutPage', 'contactPage') }),
    defineField({ name: 'office2Name', title: 'Office 2 — Name', type: 'string', group: 'sections',
      hidden: isPage('aboutPage', 'contactPage') }),
    defineField({ name: 'office2Address', title: 'Office 2 — Address', type: 'string', group: 'sections',
      hidden: isPage('aboutPage', 'contactPage') }),
    defineField({ name: 'office2Country', title: 'Office 2 — Country', type: 'string', group: 'sections',
      hidden: isPage('aboutPage', 'contactPage') }),
    defineField({ name: 'office2Description', title: 'Office 2 — Description', type: 'string', group: 'sections',
      hidden: isPage('aboutPage', 'contactPage') }),
    defineField({ name: 'office2ComingSoon', title: 'Office 2 — Coming Soon Badge', type: 'boolean', group: 'sections',
      description: 'Show a "Coming Soon" badge and dimmed style', initialValue: false,
      hidden: isPage('aboutPage', 'contactPage') }),
    // About clients wall
    defineField({ name: 'clientsLabel', title: 'Clients Wall — Section Label', type: 'string', group: 'sections', hidden: isPage('aboutPage') }),
    defineField({ name: 'clientsWallCta', title: 'Clients Wall — CTA Text', type: 'string', group: 'sections',
      description: 'e.g. "Want to appear here?" — followed by the email link', hidden: isPage('aboutPage') }),

    // ── Clients Page ────────────────────────────────────────────────────────
    defineField({ name: 'statsLabel', title: 'Stats — Section Label', type: 'string', group: 'sections', hidden: isPage('clientsPage') }),
    defineField({ name: 'stat1DisplayValue', title: 'Stat 1 — Display Value (text)', type: 'string', group: 'sections', hidden: isPage('clientsPage') }),
    defineField({ name: 'stat1DisplayLabel', title: 'Stat 1 — Label', type: 'string', group: 'sections', hidden: isPage('clientsPage') }),
    defineField({ name: 'stat2DisplayValue', title: 'Stat 2 — Display Value (text)', type: 'string', group: 'sections', hidden: isPage('clientsPage') }),
    defineField({ name: 'stat2DisplayLabel', title: 'Stat 2 — Label', type: 'string', group: 'sections', hidden: isPage('clientsPage') }),
    defineField({ name: 'stat3DisplayValue', title: 'Stat 3 — Display Value (text)', type: 'string', group: 'sections', hidden: isPage('clientsPage') }),
    defineField({ name: 'stat3DisplayLabel', title: 'Stat 3 — Label', type: 'string', group: 'sections', hidden: isPage('clientsPage') }),
    defineField({ name: 'testimonialsLabel', title: 'Testimonials — Section Label', type: 'string', group: 'sections', hidden: isPage('clientsPage') }),
    // About CTA
    defineField({ name: 'ctaHeadline', title: 'CTA — Headline', type: 'string', group: 'sections',
      hidden: isPage('aboutPage', 'servicesPage') }),
    defineField({ name: 'ctaBody', title: 'CTA — Body', type: 'text', rows: 3, group: 'sections',
      hidden: isPage('aboutPage', 'servicesPage') }),
    defineField({ name: 'ctaLabel', title: 'CTA — Button Label', type: 'string', group: 'sections',
      hidden: isPage('aboutPage', 'servicesPage', 'homepage') }),
    defineField({ name: 'ctaHref', title: 'CTA — Button URL', type: 'string', group: 'sections',
      hidden: isPage('aboutPage', 'servicesPage', 'homepage') }),

    // ── Services ────────────────────────────────────────────────────────────
    defineField({ name: 'service1Title', title: 'Service 1 — Title', type: 'string', group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'service1Body', title: 'Service 1 — Body', type: 'text', rows: 4, group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'service1Deliverable1', title: 'Service 1 — Deliverable 1', type: 'string', group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'service1Deliverable2', title: 'Service 1 — Deliverable 2', type: 'string', group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'service1Deliverable3', title: 'Service 1 — Deliverable 3', type: 'string', group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'service1Deliverable4', title: 'Service 1 — Deliverable 4', type: 'string', group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'service1Deliverable5', title: 'Service 1 — Deliverable 5', type: 'string', group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'service1ImageUrl', title: 'Service 1 — Background Image URL', type: 'url', group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'service2Title', title: 'Service 2 — Title', type: 'string', group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'service2Body', title: 'Service 2 — Body', type: 'text', rows: 4, group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'service2Deliverable1', title: 'Service 2 — Deliverable 1', type: 'string', group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'service2Deliverable2', title: 'Service 2 — Deliverable 2', type: 'string', group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'service2Deliverable3', title: 'Service 2 — Deliverable 3', type: 'string', group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'service2Deliverable4', title: 'Service 2 — Deliverable 4', type: 'string', group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'service2Deliverable5', title: 'Service 2 — Deliverable 5', type: 'string', group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'service2ImageUrl', title: 'Service 2 — Background Image URL', type: 'url', group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'service3Title', title: 'Service 3 — Title', type: 'string', group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'service3Body', title: 'Service 3 — Body', type: 'text', rows: 4, group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'service3Deliverable1', title: 'Service 3 — Deliverable 1', type: 'string', group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'service3Deliverable2', title: 'Service 3 — Deliverable 2', type: 'string', group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'service3Deliverable3', title: 'Service 3 — Deliverable 3', type: 'string', group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'service3Deliverable4', title: 'Service 3 — Deliverable 4', type: 'string', group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'service3Deliverable5', title: 'Service 3 — Deliverable 5', type: 'string', group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'service3ImageUrl', title: 'Service 3 — Background Image URL', type: 'url', group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'service4Title', title: 'Service 4 — Title', type: 'string', group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'service4Body', title: 'Service 4 — Body', type: 'text', rows: 4, group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'service4Deliverable1', title: 'Service 4 — Deliverable 1', type: 'string', group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'service4Deliverable2', title: 'Service 4 — Deliverable 2', type: 'string', group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'service4Deliverable3', title: 'Service 4 — Deliverable 3', type: 'string', group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'service4Deliverable4', title: 'Service 4 — Deliverable 4', type: 'string', group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'service4Deliverable5', title: 'Service 4 — Deliverable 5', type: 'string', group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'service4ImageUrl', title: 'Service 4 — Background Image URL', type: 'url', group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'service5Title', title: 'Service 5 — Title', type: 'string', group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'service5Body', title: 'Service 5 — Body', type: 'text', rows: 4, group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'service5Deliverable1', title: 'Service 5 — Deliverable 1', type: 'string', group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'service5Deliverable2', title: 'Service 5 — Deliverable 2', type: 'string', group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'service5Deliverable3', title: 'Service 5 — Deliverable 3', type: 'string', group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'service5Deliverable4', title: 'Service 5 — Deliverable 4', type: 'string', group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'service5Deliverable5', title: 'Service 5 — Deliverable 5', type: 'string', group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'service5ImageUrl', title: 'Service 5 — Background Image URL', type: 'url', group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'service6Title', title: 'Service 6 — Title', type: 'string', group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'service6Body', title: 'Service 6 — Body', type: 'text', rows: 4, group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'service6Deliverable1', title: 'Service 6 — Deliverable 1', type: 'string', group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'service6Deliverable2', title: 'Service 6 — Deliverable 2', type: 'string', group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'service6Deliverable3', title: 'Service 6 — Deliverable 3', type: 'string', group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'service6Deliverable4', title: 'Service 6 — Deliverable 4', type: 'string', group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'service6Deliverable5', title: 'Service 6 — Deliverable 5', type: 'string', group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'service6ImageUrl', title: 'Service 6 — Background Image URL', type: 'url', group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'serviceCtaLabel', title: 'Services — Per-Service CTA Label', type: 'string', group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'deliverablesLabel', title: 'Services — "What\'s Included" Label', type: 'string', group: 'sections', hidden: isPage('servicesPage') }),
    defineField({ name: 'ctaAccent', title: 'CTA — Accent (orange line)', type: 'string', group: 'sections',
      hidden: isPage('servicesPage') }),
    defineField({ name: 'ctaButtonLabel', title: 'CTA — Bottom Button Label', type: 'string', group: 'sections',
      hidden: isPage('servicesPage', 'homepage') }),
    defineField({ name: 'ctaButtonHref', title: 'CTA — Bottom Button URL', type: 'string', group: 'sections',
      hidden: isPage('servicesPage', 'homepage') }),

    // ── Work Page ───────────────────────────────────────────────────────────
    defineField({ name: 'filterAllLabel', title: 'Work — "All" Filter Label', type: 'string', group: 'sections',
      hidden: isPage('workPage') }),

    // ── Contact ─────────────────────────────────────────────────────────────
    defineField({ name: 'directLabel', title: 'Contact — Direct Section Label', type: 'string', group: 'sections', hidden: isPage('contactPage') }),
    defineField({ name: 'followLabel', title: 'Contact — Follow Section Label', type: 'string', group: 'sections', hidden: isPage('contactPage') }),
    defineField({ name: 'emailLabel', title: 'Contact — Email Display', type: 'string', group: 'sections', hidden: isPage('contactPage') }),
    defineField({ name: 'phoneLabel', title: 'Contact — Phone Number', type: 'string', group: 'sections', hidden: isPage('contactPage') }),
    defineField({ name: 'founderName', title: 'Contact — Founder Name', type: 'string', group: 'sections', hidden: isPage('contactPage') }),
    defineField({ name: 'founderRole', title: 'Contact — Founder Role', type: 'string', group: 'sections', hidden: isPage('contactPage') }),
    defineField({ name: 'addressLabel', title: 'Contact — Address Section Label', type: 'string', group: 'sections', hidden: isPage('contactPage') }),
    defineField({ name: 'addressLine1', title: 'Contact — Address Line 1 (city)', type: 'string', group: 'sections', hidden: isPage('contactPage') }),
    defineField({ name: 'addressLine2', title: 'Contact — Address Line 2 (street)', type: 'string', group: 'sections', hidden: isPage('contactPage') }),
    defineField({ name: 'formHeadline', title: 'Form — Headline', type: 'string', group: 'sections', hidden: isPage('contactPage') }),
    defineField({ name: 'formNameLabel', title: 'Form — Name Field Label', type: 'string', group: 'sections', hidden: isPage('contactPage') }),
    defineField({ name: 'formEmailLabel', title: 'Form — Email Field Label', type: 'string', group: 'sections', hidden: isPage('contactPage') }),
    defineField({ name: 'formCompanyLabel', title: 'Form — Company Field Label', type: 'string', group: 'sections', hidden: isPage('contactPage') }),
    defineField({ name: 'formServiceLabel', title: 'Form — Service Field Label', type: 'string', group: 'sections', hidden: isPage('contactPage') }),
    defineField({ name: 'formBudgetLabel', title: 'Form — Budget Field Label', type: 'string', group: 'sections', hidden: isPage('contactPage') }),
    defineField({ name: 'formMessageLabel', title: 'Form — Message Field Label', type: 'string', group: 'sections', hidden: isPage('contactPage') }),
    defineField({ name: 'formButtonLabel', title: 'Form — Submit Button Label', type: 'string', group: 'sections', hidden: isPage('contactPage') }),
    defineField({ name: 'formPrivacyDisclaimer', title: 'Form — Privacy Disclaimer (text below submit)', type: 'text', rows: 2, group: 'sections', hidden: isPage('contactPage') }),
    defineField({ name: 'formSuccessTitle', title: 'Form — Success Title', type: 'string', group: 'sections', hidden: isPage('contactPage') }),
    defineField({ name: 'formSuccessBody', title: 'Form — Success Body', type: 'text', rows: 2, group: 'sections', hidden: isPage('contactPage') }),

    // ── Careers ─────────────────────────────────────────────────────────────
    defineField({ name: 'perksHeadline', title: 'Perks — Section Headline', type: 'string', group: 'sections', hidden: isPage('careersPage') }),
    defineField({ name: 'rolesLabel', title: 'Open Roles — Label', type: 'string', group: 'sections', hidden: isPage('careersPage') }),
    defineField({ name: 'noPositionsHeadline', title: 'No Positions — Headline', type: 'string', group: 'sections', hidden: isPage('careersPage') }),
    defineField({ name: 'noPositionsBody', title: 'No Positions — Body', type: 'text', rows: 3, group: 'sections', hidden: isPage('careersPage') }),
    defineField({ name: 'spontaneousLabel', title: 'Spontaneous — Eyebrow Label', type: 'string', group: 'sections', hidden: isPage('careersPage') }),
    defineField({ name: 'spontaneousHeadline', title: 'Spontaneous — Headline', type: 'string', group: 'sections', hidden: isPage('careersPage') }),
    defineField({ name: 'spontaneousBody', title: 'Spontaneous — Body', type: 'text', rows: 4, group: 'sections', hidden: isPage('careersPage') }),
    defineField({ name: 'perk1Title', title: 'Perk 1 — Title', type: 'string', group: 'sections', hidden: isPage('careersPage') }),
    defineField({ name: 'perk1Body', title: 'Perk 1 — Body', type: 'text', rows: 3, group: 'sections', hidden: isPage('careersPage') }),
    defineField({ name: 'perk2Title', title: 'Perk 2 — Title', type: 'string', group: 'sections', hidden: isPage('careersPage') }),
    defineField({ name: 'perk2Body', title: 'Perk 2 — Body', type: 'text', rows: 3, group: 'sections', hidden: isPage('careersPage') }),
    defineField({ name: 'perk3Title', title: 'Perk 3 — Title', type: 'string', group: 'sections', hidden: isPage('careersPage') }),
    defineField({ name: 'perk3Body', title: 'Perk 3 — Body', type: 'text', rows: 3, group: 'sections', hidden: isPage('careersPage') }),
    defineField({ name: 'perk4Title', title: 'Perk 4 — Title', type: 'string', group: 'sections', hidden: isPage('careersPage') }),
    defineField({ name: 'perk4Body', title: 'Perk 4 — Body', type: 'text', rows: 3, group: 'sections', hidden: isPage('careersPage') }),
    defineField({ name: 'perk5Title', title: 'Perk 5 — Title', type: 'string', group: 'sections', hidden: isPage('careersPage') }),
    defineField({ name: 'perk5Body', title: 'Perk 5 — Body', type: 'text', rows: 3, group: 'sections', hidden: isPage('careersPage') }),

    // ── Legal Pages (Privacy & Cookie) ──────────────────────────────────────
    defineField({
      name: 'legalLastUpdated',
      title: 'Legal — Last Updated',
      type: 'string',
      description: 'E.g. "January 2026"',
      group: 'sections',
      hidden: isPage('privacyPage', 'cookiePage'),
    }),
    defineField({
      name: 'legalBody',
      title: 'Legal — Body Content',
      type: 'array',
      group: 'sections',
      hidden: isPage('privacyPage', 'cookiePage'),
      of: [
        {
          type: 'block',
          styles: [
            { title: 'Normal', value: 'normal' },
            { title: 'H2', value: 'h2' },
            { title: 'H3', value: 'h3' },
          ],
          lists: [
            { title: 'Bullet', value: 'bullet' },
            { title: 'Number', value: 'number' },
          ],
          marks: {
            decorators: [
              { title: 'Strong', value: 'strong' },
              { title: 'Emphasis', value: 'em' },
            ],
            annotations: [
              {
                name: 'link',
                type: 'object',
                title: 'Link',
                fields: [{ name: 'href', type: 'url', title: 'URL' }],
              },
            ],
          },
        },
      ],
    }),

    // ── Blog Index Labels ───────────────────────────────────────────────────
    defineField({ name: 'blogFeaturedLabel', title: 'Blog — Featured Label', type: 'string', group: 'sections', hidden: isPage('blogPage') }),
    defineField({ name: 'blogLatestLabel', title: 'Blog — Latest Label', type: 'string', group: 'sections', hidden: isPage('blogPage') }),
    defineField({ name: 'blogReadMoreLabel', title: 'Blog — Read More Label', type: 'string', group: 'sections', hidden: isPage('blogPage') }),

    // ── SEO (all pages) ─────────────────────────────────────────────────────
    defineField({ name: 'seoTitle', title: 'SEO Title', type: 'string', group: 'seo' }),
    defineField({ name: 'seoDescription', title: 'SEO Description', type: 'text', rows: 3, group: 'seo' }),
  ],
  preview: {
    select: { title: 'pageId', subtitle: 'language', published: 'isPublished' },
    prepare({ title, subtitle, published }) {
      const pageLabels: Record<string, string> = {
        homepage: 'Homepage',
        aboutPage: 'About',
        servicesPage: 'Services',
        workPage: 'Work',
        clientsPage: 'Clients',
        contactPage: 'Contact',
        careersPage: 'Careers',
        blogPage: 'Blog',
        privacyPage: 'Privacy Policy',
        cookiePage: 'Cookie Policy',
      }
      return {
        title: `${pageLabels[title as string] ?? title} — ${(subtitle as string ?? '').toUpperCase()}`,
        subtitle: published === false ? 'DRAFT' : 'Published',
      }
    },
  },
})

export default pageContent
